### ISSUE TITLE
Issue with media Manager Demo application

### ISSUE THREAD

**Issue by UmarDastgir** [DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo#1]
I recently tried installing MediaManagerDemo application and ran into an issue which I believe has to do with the libraries provided for DJI development. The Default Layout Activity has a button programmed to call the media manager class (button id is btn_mediaManager). The first time this button is clicked, it works perfectly (opens the media manager and I can see all files present on DJI). However, when I click "BACK" and try to re-open this activity using btn_mediaManager button, the app keeps on loading and no picture/video is shown. I am using Phantom 3 Advanced and Samsung Galaxy S5 for the app. I have also tried using a different Phantom 3 Advanced and a different cell phone but the same problem persists. Any help regarding this will be appreciated.

Drone used: Phantom 3 Advanced
Cell phone and Android Version: Samsung Galaxy S5, Lollipop 5.0
Android Studio Version 2.3.3

The two screenshots below show the issue. One of them is when everything works fine. The second is when it keeps on loading. I did read the description and found out that Phantom 3 Advanced is not mentioned in the list of supported drones. However, I have worked a lot with almost all tutorials on DJI website and all of them work perfectly on Phantom 3 Advanced. 

![screenshot_2017-10-23-13-53-25](https://user-images.githubusercontent.com/17656434/31910570-28640798-b7fb-11e7-8ce9-89c30b9f79b1.png)
![screenshot_2017-10-23-13-54-55](https://user-images.githubusercontent.com/17656434/31910571-287d0ffe-b7fb-11e7-94f1-8596d81dfdae.png)

**Comment by oliverou** [comment]
Hi @UmarDastgir , thanks for your feedbacks! We have addressed the issue, it seems that this issue also exists on other products. Will get back to you once you make any progress.

**Comment by oliverou** [comment]
Hi @UmarDastgir, the bug is already fixed, please get the latest code of the demo and try again.

**Comment by UmarDastgir** [comment]
Thank a lot for the help. Works perfectly.
