### ISSUE TITLE
GeoTIFF

### ISSUE THREAD

**Issue by Asendo316** [DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo#11]
How do i capture GeoTIFF images with the DJI SDK on my Matrice 100 ?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36393'>Zendesk ticket #36393</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
You can set the tiff photo file format with method setPhotoFileFormat.
 ![](https://djisdksupport.zendesk.com/attachments/token/5UuwIr90IZsL9q9muxuSMWySx/?name=inline2092776958.png)​

Thanks,

Luce Luo
DJI Dev Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/5UuwIr90IZsL9q9muxuSMWySx' target='zd_attach'>inline2092776958.png</a>

**Comment by Asendo316** [comment]
Does this work for Z3 Camera please?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36393'>Zendesk ticket #36393</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
No, the Z3 camera can't set the tiff format.
The tiff format is for the thermal camera.

Thanks,

Luce Luo
DJI Dev Team

**Comment by Asendo316** [comment]
Thanks
