### ISSUE TITLE
Camera Stream not visible

### ISSUE THREAD

**Issue by UmarDastgir** [DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo#2]
I recently tried installing the Media Manager Demo application and I have come across another bug. Upon going from the DefaultLayoutActivity (with the live camera stream) to the MainActivity (Media Manager), everything works fine. However, upon pressing the back button (in the MainActivity), the live stream of camera is no longer visible. This can be seen in the screenshots below. 

Drone used: Phantom 3 Advanced
Cell phone and Android Version: Samsung Galaxy S5, Lollipop 5.0
Android Studio Version 2.3.3

![screenshot_2017-10-24-18-29-44 1](https://user-images.githubusercontent.com/17656434/31974562-ae2a5578-b8e9-11e7-9448-67c529b3ca93.png)
![screenshot_2017-10-24-18-29-52 1](https://user-images.githubusercontent.com/17656434/31974567-b3015916-b8e9-11e7-9043-cd21938290b7.png)

In the first picture, the live stream is clearly visible. When I press the button in the bottom right and then press back, the live stream is no longer visible (second screenshot).

**Comment by oliverou** [comment]
Hi @UmarDastgir , thanks for the feedbacks. We have addressed this issue and will fix it in the DJI Android UILibrary of the next release. Currently, we can provide a workaround for you:

Add the following code in **MainActivity.java** file to start the DefaultLayoutActivity:

~~~java
    @Override
    public void finish() {
        Intent intent = new Intent(this, DefaultLayoutActivity.class);
        startActivity(intent);
        super.finish();
    }
~~~

In the **DefaultLayoutActivity.java** file, add the following code below `startActivity(intent);` in the `onClick()` method to close the activity when the button is clicked:

~~~java
     finish();
~~~

**Comment by UmarDastgir** [comment]
Works perfectly. Thanks.
