### ISSUE TITLE
Capturing, but not showing anything in the app

### ISSUE THREAD

**Issue by aRealBanana** [DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo#5]
So I ran into a problem when i cloned this project, when I take a picture or video they are being taken but when I click on the button to take me to media it says that there is nothing to be shown! but when I use the official DJI GO 4 app I can veiw the media that was taken in the mediaManagerDemo app. Also in MainActivity i have this warning "'android.widget.SlidingDrawer' is deprecated as of API 17: Android 4.2 (Jelly Bean) less... (Ctrl+F1) 
Inspection info: This inspection reports where deprecated code is used in the specified inspection scope." am not sure if its what cosing the problem or something else.

Using latest Dji sdk, latest android studio and latest android update on Huawei mate 20 pro.

**Comment by aRealBanana** [comment]
I found where the problem was, I was using 32 GB sd card and for somereason the Drone does not recognize it, changed the sd card to 128 GB and now the media gets stored in the sd card instead of the internal storage which this application does not show, only sd card media.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/27711'>Zendesk ticket #27711</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
