### ISSUE TITLE
Video doesn't shows preview or plays

### ISSUE THREAD

**Issue by mnabilurrehman** [DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo#6]
I have build the MediaManagerSDK it is working fine for capturing photos, record audio and downloading video and picture. But it only shows Preview of photo when I press on video it doesn't shows it preview or doesn't play it.

After making video when I press on video item following happens in addMediaTask function.

In onUpdate() call back DJIError is not null and it executes the else block:
} else {
    setResultToToast("fetch preview image failed: " + error.getDescription());
}
and shows:
"fetch preview image failed: Media download result: the server aborts the downloading"

Tested it on Mavic Pro and Spark

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/28466'>Zendesk ticket #28466</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by mnabilurrehman** [comment]
Thank you for your response. Issue was resolved after after contacting DJI Support. It was an issue from usability side. (y)

**Comment by Asendo316** [comment]
What was the solution to this please?
